name: iJungle
favicon: null
layout_spectrum: 0.8118870812468231
typography_spectrum: 0.5408097198233008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3013508303556591
  lightness: 0.6430631978437304
  saturation: 0.5576455243863165
  rhythmicContrast: 0.7969827961642295
purpose: []
